matrix:
  include:
    - os: linux
      language: node_js
      node_js: "6"
      env:
        - TRAVIS=true
    - os: linux
      language: node_js
      node_js: "8"
      env:
        - TRAVIS=true
    - os: osx
      language: node_js
      node_js: "6"
      env:
        - TRAVIS=true
    - os: osx
      language: node_js
      node_js: "8"
      env:
        - TRAVIS=true
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: "6"
      env:
        - TRAVIS=true
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: "8"
      env:
        - TRAVIS=true
cache:
  directories:
    - "node_modules"
script:
  - npm run test:ci
